apiVersion: apps.example.com/v1alpha1
kind: NginxCluster
metadata:
  labels:
    app.kubernetes.io/name: nginx-operator
    app.kubernetes.io/managed-by: kustomize
  name: nginxcluster-sample
spec:
  # TODO(user): Add fields here
